// Updated EUDR HS Codes and Commodity Groups
export const EUDR_HS_CODES = [
    { code: "0102", commodity: "Cattle – Live bovine animals", group: "Cattle" },
    { code: "0201", commodity: "Cattle – Meat of bovine animals, fresh or chilled", group: "Cattle" },
    { code: "0202", commodity: "Cattle – Meat of bovine animals, frozen", group: "Cattle" },
    { code: "0206 10", commodity: "Cattle – Edible offal of bovine animals, fresh or chilled", group: "Cattle" },
    { code: "0206 22", commodity: "Cattle – Edible offal of bovine animals, frozen livers", group: "Cattle" },
    { code: "0206 29", commodity: "Cattle – Edible offal of bovine animals, frozen other", group: "Cattle" },
    { code: "1602 50", commodity: "Cattle – Prepared or preserved meat of bovine animals", group: "Cattle" },
    { code: "4101", commodity: "Cattle – Raw hides and skins of bovine animals", group: "Cattle" },
    { code: "4104", commodity: "Cattle – Tanned or crust hides and skins of bovine animals", group: "Cattle" },
    { code: "4107", commodity: "Cattle – Leather further prepared after tanning or crusting", group: "Cattle" },
  
    { code: "1801", commodity: "Cocoa – Cocoa beans, whole or broken, raw or roasted", group: "Cocoa" },
    { code: "1802", commodity: "Cocoa – Cocoa shells, husks, skins and other cocoa waste", group: "Cocoa" },
    { code: "1803", commodity: "Cocoa – Cocoa paste, whether or not defatted", group: "Cocoa" },
    { code: "1804", commodity: "Cocoa – Cocoa butter, fat and oil", group: "Cocoa" },
    { code: "1805", commodity: "Cocoa – Cocoa powder, not containing added sugar", group: "Cocoa" },
    { code: "1806", commodity: "Cocoa – Chocolate and other food preparations containing cocoa", group: "Cocoa" },
  
    { code: "0901", commodity: "Coffee – Coffee, whether or not roasted or decaffeinated", group: "Coffee" },
  
    { code: "1511", commodity: "Palm Oil – Palm oil and its fractions, whether or not refined", group: "Palm Oil" },
    { code: "1513 21", commodity: "Palm Oil – Palm kernel or babassu oil, crude", group: "Palm Oil" },
    { code: "1513 29", commodity: "Palm Oil – Palm kernel or babassu oil, refined", group: "Palm Oil" },
    { code: "2306 60", commodity: "Palm Oil – Oil-cake and other solid residues from palm nuts", group: "Palm Oil" },
    { code: "2905 45", commodity: "Palm Oil – Glycerol", group: "Palm Oil" },
    { code: "3823 11", commodity: "Palm Oil – Stearic acid", group: "Palm Oil" },
    { code: "3823 12", commodity: "Palm Oil – Oleic acid", group: "Palm Oil" },
    { code: "3823 19", commodity: "Palm Oil – Industrial monocarboxylic fatty acids, other", group: "Palm Oil" },
  
    { code: "4001", commodity: "Rubber – Natural rubber, balata, gutta-percha", group: "Rubber" },
    { code: "4005", commodity: "Rubber – Compounded rubber, unvulcanised", group: "Rubber" },
    { code: "4006", commodity: "Rubber – Unvulcanised rubber in other forms", group: "Rubber" },
    { code: "4007", commodity: "Rubber – Vulcanised rubber thread and cord", group: "Rubber" },
    { code: "4008", commodity: "Rubber – Plates, sheets, strip, rods and profile shapes", group: "Rubber" },
    { code: "4010", commodity: "Rubber – Conveyor or transmission belts or belting", group: "Rubber" },
    { code: "4011", commodity: "Rubber – New pneumatic tyres", group: "Rubber" },
    { code: "4012", commodity: "Rubber – Retreaded or used pneumatic tyres", group: "Rubber" },
    { code: "4013", commodity: "Rubber – Inner tubes", group: "Rubber" },
    { code: "4015", commodity: "Rubber – Articles of apparel and clothing accessories", group: "Rubber" },
    { code: "4016", commodity: "Rubber – Other articles of vulcanised rubber", group: "Rubber" },
    { code: "4017", commodity: "Rubber – Hard rubber in all forms", group: "Rubber" },
  
    { code: "1201", commodity: "Soy – Soya beans, whether or not broken", group: "Soy" },
    { code: "1208 10", commodity: "Soy – Flours and meals of soya beans", group: "Soy" },
    { code: "1507", commodity: "Soy – Soya-bean oil and its fractions", group: "Soy" },
    { code: "2304", commodity: "Soy – Oil-cake and other solid residues from soya-bean oil", group: "Soy" },
  
    { code: "4401", commodity: "Wood – Fuel wood, in logs, in billets, in twigs", group: "Wood" },
    { code: "4403", commodity: "Wood – Wood in the rough", group: "Wood" },
    { code: "4406", commodity: "Wood – Railway or tramway sleepers", group: "Wood" },
    { code: "4407", commodity: "Wood – Wood sawn or chipped lengthwise", group: "Wood" },
    { code: "4408", commodity: "Wood – Sheets for veneering", group: "Wood" },
    { code: "4409", commodity: "Wood – Wood continuously shaped along any of its edges", group: "Wood" },
    { code: "4410", commodity: "Wood – Particle board, oriented strand board", group: "Wood" },
    { code: "4411", commodity: "Wood – Fibreboard of wood or other ligneous materials", group: "Wood" },
    { code: "4412", commodity: "Wood – Plywood, veneered panels and similar laminated wood", group: "Wood" },
    { code: "4413", commodity: "Wood – Densified wood", group: "Wood" },
    { code: "4414", commodity: "Wood – Wooden frames for paintings, photographs, mirrors", group: "Wood" },
    { code: "4415", commodity: "Wood – Packing cases, boxes, crates, drums", group: "Wood" },
    { code: "4416", commodity: "Wood – Casks, barrels, vats, tubs", group: "Wood" },
    { code: "4418", commodity: "Wood – Builders' joinery and carpentry of wood", group: "Wood" },
    { code: "4419", commodity: "Wood – Tableware and kitchenware, of wood", group: "Wood" },
    { code: "4420", commodity: "Wood – Wood marquetry and inlaid wood; caskets and cases", group: "Wood" },
    { code: "4421", commodity: "Wood – Other articles of wood", group: "Wood" },
    { code: "4701", commodity: "Wood – Mechanical wood pulp", group: "Wood" },
    { code: "4703", commodity: "Wood – Chemical wood pulp, soda or sulphate", group: "Wood" },
    { code: "4704", commodity: "Wood – Chemical wood pulp, sulphite", group: "Wood" },
    { code: "4705", commodity: "Wood – Wood pulp obtained by a combination of mechanical and chemical processes", group: "Wood" },
    { code: "4802", commodity: "Wood – Uncoated paper and paperboard", group: "Wood" },
    { code: "4804", commodity: "Wood – Uncoated kraft paper and paperboard", group: "Wood" },
    { code: "4805", commodity: "Wood – Other uncoated paper and paperboard", group: "Wood" },
    { code: "4806", commodity: "Wood – Vegetable parchment, greaseproof papers", group: "Wood" },
    { code: "4807", commodity: "Wood – Composite paper and paperboard", group: "Wood" },
    { code: "4808", commodity: "Wood – Paper and paperboard, corrugated, creped", group: "Wood" },
    { code: "4809", commodity: "Wood – Carbon paper, self-copy paper", group: "Wood" },
    { code: "4810", commodity: "Wood – Paper and paperboard, coated with kaolin", group: "Wood" },
    { code: "4811", commodity: "Wood – Paper, paperboard, cellulose wadding, coated, impregnated", group: "Wood" },
    { code: "4818", commodity: "Wood – Toilet paper and similar paper, cellulose wadding", group: "Wood" },
    { code: "4819", commodity: "Wood – Cartons, boxes, cases, bags and other packing containers", group: "Wood" },
    { code: "4820", commodity: "Wood – Registers, account books, note books, order books", group: "Wood" },
    { code: "4823", commodity: "Wood – Other paper, paperboard, cellulose wadding and webs", group: "Wood" },
    { code: "9401", commodity: "Wood – Seats (other than those of heading 9402)", group: "Wood" },
    { code: "9403", commodity: "Wood – Other furniture and parts thereof", group: "Wood" },
    { code: "9406 10", commodity: "Wood – Prefabricated buildings of wood", group: "Wood" }
  ];
  
  export const EUDR_RISK_MAP = {
      "High": ["Brazil", "Indonesia", "Malaysia", "Argentina", "Paraguay"],
      "Standard": ["China", "India", "Vietnam", "Turkey", "Thailand", "Ivory Coast"],
      "Low": ["Germany", "France", "Netherlands", "Sweden", "USA", "Canada", "Finland"]
  };