import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BookOpen, Search, FileText, HelpCircle, Lightbulb, Scale, ExternalLink } from "lucide-react";

const KNOWLEDGE_BASE = {
  basic: [
    { code: 'B1', title: 'Basis for Preparation', description: 'Company details, size, activities, legal form', category: 'general', guide: 'Provide basic company information including NACE code, employee count, turnover, and legal structure. Use dropdown for standardized fields.' },
    { code: 'B2', title: 'Sustainability Practices & Policies', description: 'Existing or planned sustainability initiatives', category: 'general', guide: 'Describe any ESG-related policies, targets, or transition initiatives. Upload policy documents if available.' },
    { code: 'B3', title: 'Energy & GHG Emissions', description: 'Energy consumption and Scope 1 & 2 emissions', category: 'environmental', guide: 'Report total energy (MWh) by type and GHG emissions (tCO2e). Use DEFRA, IPCC, or GHG Protocol emission factors. Upload utility bills.' },
    { code: 'B4', title: 'Pollutant Emissions', description: 'Air, water, soil pollutants', category: 'environmental', guide: 'Only required if legally mandated. Report pollutant types and amounts from permits or monitoring data.' },
    { code: 'B5', title: 'Biodiversity Impact', description: 'Sites near protected areas', category: 'environmental', guide: 'Number and area of sites in or near biodiversity-sensitive locations. Use GIS data or environmental assessments.' },
    { code: 'B6', title: 'Water Withdrawal & Consumption', description: 'Water usage data', category: 'environmental', guide: 'Total water withdrawn and consumed (m³). Include water stress zone data if available.' },
    { code: 'B7', title: 'Resource Use & Circular Economy', description: 'Waste and circularity practices', category: 'environmental', guide: 'Report waste generated by type, recycling rates, and circular economy principles applied.' },
    { code: 'B8', title: 'Workforce Characteristics', description: 'Employee composition', category: 'social', guide: 'Headcount/FTE by contract type, gender, and location. Upload HR export or payroll summary.' },
    { code: 'B9', title: 'Health & Safety', description: 'Work-related incidents', category: 'social', guide: 'Number of recordable accidents, fatalities, and occupational illnesses. Source from incident logs.' },
    { code: 'B10', title: 'Employee Rights & Development', description: 'Remuneration and training', category: 'social', guide: 'Report wage data, gender pay gap, collective bargaining coverage, and training hours per employee.' },
    { code: 'B11', title: 'Corruption & Bribery', description: 'Convictions and fines', category: 'governance', guide: 'Only if convictions occurred. Report number and total fines during reporting period.' }
  ],
  comprehensive: [
    { code: 'C1', title: 'Business Model & Strategy', description: 'ESG integration in strategy', category: 'general', guide: 'Describe how sustainability is embedded in business model. Minimum 300 characters. Upload strategy documents.' },
    { code: 'C2', title: 'Transition Practices', description: 'Future ESG initiatives', category: 'general', guide: 'Detail transition policies and future action plans with milestones. Assign responsible persons.' },
    { code: 'C3', title: 'GHG Reduction Targets', description: 'Climate targets and plans', category: 'environmental', guide: 'Set time-bound GHG reduction targets with base year, target year, and implementation plan.' },
    { code: 'C4', title: 'Climate Risks & Adaptation', description: 'Physical and transition risks', category: 'environmental', guide: 'Identify climate-related risks (floods, droughts, carbon taxes) and adaptation measures.' },
    { code: 'C5', title: 'Extended Workforce Data', description: 'Management diversity, contractors', category: 'social', guide: 'Report management gender ratio, temporary workers %, and non-EU worker count.' },
    { code: 'C6', title: 'Human Rights Policies', description: 'Workforce rights protection', category: 'social', guide: 'Document HR policies covering fair wage, safe workplace, and freedom of association.' },
    { code: 'C7', title: 'Human Rights Incidents', description: 'Severe incidents and actions', category: 'social', guide: 'Report any serious human rights breaches and corrective actions. Include whistleblower mechanisms.' },
    { code: 'C8', title: 'Critical Sector Revenues', description: 'EU Taxonomy exclusions', category: 'governance', guide: 'Declare revenue from excluded sectors (fossil fuels, arms, tobacco). 0% if claiming EU alignment.' },
    { code: 'C9', title: 'Governance Gender Diversity', description: 'Board composition', category: 'governance', guide: 'Report gender ratio in governance body. Must total 100%. Upload diversity policy if exists.' }
  ],
  principles: [
    { title: 'Relevant', description: 'Information must be meaningful and have direct impact on sustainability performance' },
    { title: 'Faithful', description: 'Information must be accurate and unbiased, truthfully representing sustainability matters' },
    { title: 'Comparable', description: 'Disclosures should be comparable over time and against other companies' },
    { title: 'Understandable', description: 'Information must be clear and concise for stakeholders to easily comprehend' },
    { title: 'Verifiable', description: 'Data should be complete, neutral, and accurate for independent verification' }
  ]
};

export default function VSMEKnowledgeHub() {
  const [searchTerm, setSearchTerm] = useState('');
  const [activeTab, setActiveTab] = useState('basic');

  const filterDisclosures = (disclosures) => {
    if (!searchTerm) return disclosures;
    return disclosures.filter(d =>
      d.code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      d.title?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      d.description?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      d.guide?.toLowerCase().includes(searchTerm.toLowerCase())
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="bg-gradient-to-r from-[#86b027]/5 to-white border-[#86b027]/20">
        <CardContent className="p-6">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-[#86b027]/10 rounded-xl">
              <BookOpen className="w-7 h-7 text-[#86b027]" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-[#545454]">VSME Knowledge Hub</h2>
              <p className="text-sm text-slate-600 mt-1">
                EFRAG guidance, disclosure requirements, and best practices for VSME reporting
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
        <Input
          placeholder="Search disclosures, guides, principles..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="pl-10"
        />
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="bg-white border border-slate-200">
          <TabsTrigger value="basic" className="gap-2">
            <FileText className="w-4 h-4" />
            Basic Module (B1-B11)
          </TabsTrigger>
          <TabsTrigger value="comprehensive" className="gap-2">
            <FileText className="w-4 h-4" />
            Comprehensive (C1-C9)
          </TabsTrigger>
          <TabsTrigger value="principles" className="gap-2">
            <Scale className="w-4 h-4" />
            EFRAG Principles
          </TabsTrigger>
          <TabsTrigger value="resources" className="gap-2">
            <ExternalLink className="w-4 h-4" />
            Resources
          </TabsTrigger>
        </TabsList>

        <TabsContent value="basic" className="space-y-3">
          {filterDisclosures(KNOWLEDGE_BASE.basic).map(item => (
            <Card key={item.code} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Badge className="bg-[#86b027]">{item.code}</Badge>
                  <span className="font-bold text-[#545454]">{item.title}</span>
                  <Badge variant="outline" className="ml-auto text-xs">{item.category}</Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <p className="text-sm text-slate-600">{item.description}</p>
                <div className="bg-slate-50 p-3 rounded-lg border border-slate-200">
                  <div className="flex items-start gap-2">
                    <Lightbulb className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                    <div>
                      <p className="text-xs font-medium text-slate-700 mb-1">Implementation Guide</p>
                      <p className="text-xs text-slate-600">{item.guide}</p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </TabsContent>

        <TabsContent value="comprehensive" className="space-y-3">
          {filterDisclosures(KNOWLEDGE_BASE.comprehensive).map(item => (
            <Card key={item.code} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Badge className="bg-[#02a1e8]">{item.code}</Badge>
                  <span className="font-bold text-[#545454]">{item.title}</span>
                  <Badge variant="outline" className="ml-auto text-xs">{item.category}</Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <p className="text-sm text-slate-600">{item.description}</p>
                <div className="bg-slate-50 p-3 rounded-lg border border-slate-200">
                  <div className="flex items-start gap-2">
                    <Lightbulb className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                    <div>
                      <p className="text-xs font-medium text-slate-700 mb-1">Implementation Guide</p>
                      <p className="text-xs text-slate-600">{item.guide}</p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </TabsContent>

        <TabsContent value="principles" className="space-y-3">
          <Card className="border-[#86b027]/20">
            <CardHeader>
              <CardTitle className="text-base">VSME Reporting Principles</CardTitle>
              <p className="text-sm text-slate-600">Five key principles ensuring reliability and usability per EFRAG</p>
            </CardHeader>
            <CardContent className="space-y-3">
              {KNOWLEDGE_BASE.principles.map((principle, idx) => (
                <div key={idx} className="flex items-start gap-3 p-3 bg-slate-50 rounded-lg">
                  <div className="w-8 h-8 rounded-full bg-[#86b027] text-white flex items-center justify-center shrink-0 text-sm font-bold">
                    {idx + 1}
                  </div>
                  <div>
                    <h4 className="font-bold text-[#545454] text-sm">{principle.title}</h4>
                    <p className="text-xs text-slate-600 mt-1">{principle.description}</p>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="resources" className="space-y-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <ExternalLink className="w-5 h-5" />
                Official EFRAG Resources
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {[
                { title: 'EFRAG VSME Standard (December 2024)', url: 'https://www.efrag.org/lab6', tag: 'Official Standard' },
                { title: 'ESRS Overview & Guidance', url: 'https://www.efrag.org/lab3', tag: 'Reference' },
                { title: 'GHG Protocol Guidance', url: 'https://ghgprotocol.org/', tag: 'Calculation' },
                { title: 'EU SME ESRS Guidance 2024', url: 'https://finance.ec.europa.eu/', tag: 'EU Resource' }
              ].map((resource, idx) => (
                <a
                  key={idx}
                  href={resource.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-between p-4 border border-slate-200 rounded-lg hover:border-[#86b027] hover:shadow-md transition-all group"
                >
                  <div>
                    <h4 className="font-medium text-[#545454] group-hover:text-[#86b027] transition-colors text-sm">
                      {resource.title}
                    </h4>
                    <Badge variant="outline" className="mt-1 text-xs">{resource.tag}</Badge>
                  </div>
                  <ExternalLink className="w-4 h-4 text-slate-400 group-hover:text-[#86b027] transition-colors" />
                </a>
              ))}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <HelpCircle className="w-5 h-5" />
                Common Questions
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {[
                { q: 'What is the "if applicable" principle?', a: 'You only need to disclose data if it\'s relevant to your business operations. This reduces reporting burden for SMEs.' },
                { q: 'Do I need external assurance?', a: 'No, external assurance is optional for VSME. However, it can enhance credibility and stakeholder trust.' },
                { q: 'Can I start with Basic and upgrade later?', a: 'Yes! You must complete the Basic Module first, then you can add Comprehensive Module disclosures as needed.' },
                { q: 'How often should I update disclosures?', a: 'Annually at minimum, or when significant changes occur in your operations or strategy.' }
              ].map((faq, idx) => (
                <div key={idx} className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <h5 className="font-bold text-[#545454] text-sm mb-2">{faq.q}</h5>
                  <p className="text-xs text-slate-600">{faq.a}</p>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}