/**
 * CONTRACT 2: Work Item Enums & Constants
 * Deterministic, append-only decision logging with reason codes and resolution strategies
 */

export const WORK_ITEM_TYPES = {
  REVIEW: 'REVIEW',
  EXTRACTION: 'EXTRACTION',
  MAPPING: 'MAPPING',
  CONFLICT: 'CONFLICT'
} as const;

export const WORK_ITEM_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  BLOCKED: 'BLOCKED',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  DONE: 'DONE'
} as const;

export const WORK_ITEM_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
} as const;

// Required reason codes for decisions
export const REASON_CODES = {
  // REVIEW decisions
  DATA_QUALITY_VERIFIED: 'DATA_QUALITY_VERIFIED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  REQUIRES_CORRECTION: 'REQUIRES_CORRECTION',
  APPROVED_WITH_CAVEATS: 'APPROVED_WITH_CAVEATS',
  
  // EXTRACTION decisions
  EXTRACTION_VERIFIED: 'EXTRACTION_VERIFIED',
  NEEDS_REWORK: 'NEEDS_REWORK',
  PARTIAL_SUCCESS: 'PARTIAL_SUCCESS',
  
  // MAPPING decisions
  HIGH_CONFIDENCE_MATCH: 'HIGH_CONFIDENCE_MATCH',
  MANUAL_VERIFICATION: 'MANUAL_VERIFICATION',
  NO_MATCH_FOUND: 'NO_MATCH_FOUND',
  REQUIRES_ADDITIONAL_DATA: 'REQUIRES_ADDITIONAL_DATA',
  
  // CONFLICT decisions
  PREFER_SOURCE_A: 'PREFER_SOURCE_A',
  PREFER_SOURCE_B: 'PREFER_SOURCE_B',
  PREFER_NEWEST_EVIDENCE: 'PREFER_NEWEST_EVIDENCE',
  PREFER_TRUSTED_SYSTEM: 'PREFER_TRUSTED_SYSTEM',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',
  ESCALATE_TO_OWNER: 'ESCALATE_TO_OWNER',
  MARK_NOT_MATERIAL: 'MARK_NOT_MATERIAL',
  
  // Follow-up triggers
  REQUEST_ADDITIONAL_EVIDENCE: 'REQUEST_ADDITIONAL_EVIDENCE',
  EVIDENCE_LINK_BROKEN: 'EVIDENCE_LINK_BROKEN'
} as const;

// Resolution strategies for CONFLICT type work items
export const CONFLICT_RESOLUTION_STRATEGIES = {
  PREFER_SOURCE_A: 'PREFER_SOURCE_A',
  PREFER_SOURCE_B: 'PREFER_SOURCE_B',
  PREFER_NEWEST_EVIDENCE: 'PREFER_NEWEST_EVIDENCE',
  PREFER_TRUSTED_SYSTEM: 'PREFER_TRUSTED_SYSTEM',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',
  DEFER_AND_REQUEST_EVIDENCE: 'DEFER_AND_REQUEST_EVIDENCE',
  MARK_NOT_MATERIAL: 'MARK_NOT_MATERIAL',
  ESCALATE_TO_OWNER: 'ESCALATE_TO_OWNER'
} as const;

// Decision types for append-only log
export const DECISION_TYPES = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  RESOLVE_CONFLICT: 'RESOLVE_CONFLICT',
  REQUEST_CORRECTION: 'REQUEST_CORRECTION',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE'
} as const;

// Trusted data sources for PREFER_TRUSTED_SYSTEM strategy
export const TRUSTED_DATASETS = ['SUPPLIER_MASTER', 'ERP_SYNC', 'ERP_API'];